project:
  type: website

website:
  title: "Benjamin Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: notebooks/page1.ipynb
        text: Page 1
      - href: notebooks/page2.ipynb
        text: Page 2

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



